tweet-map/tweet_map/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
import app.views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  re_path(r'^$', RedirectView.as_view(url='/tweets/', permanent=True)),
                  re_path(r'^tweets/$', app.views.TweetListView.as_view(), name='tweet_list'),
                  re_path(r'^map$', app.views.TweetMapView.as_view(), name='tweet_map'),
                  re_path(r'^countries/$', app.views.CountryListView.as_view(), name='countries'),
                  re_path(r'^countries/(?P<pk>\d+)$', app.views.CountryDetailView.as_view(), name='country_detail'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tweet-map/app/models.py
from django.db import models
from django.urls import reverse
import requests
from requests_oauthlib import OAuth1
import csv


class Country(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=10)
    longitude = models.CharField(max_length=20)
    latitude = models.CharField(max_length=20)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('country_detail', args=[str(self.id)])

    @staticmethod
    def populate():
        with open('assignment/countries.csv') as f:
            reader = csv.reader(f)
            for row in reader:
                if row and row[0]:
                    try:
                        obj = Country.objects.get(name=row[0], code=row[1], longitude=row[2], latitude=row[3])
                    except Country.DoesNotExist:
                        obj = Country(name=row[0], code=row[1], longitude=row[2], latitude=row[3])
                        obj.save()


class Tweet(models.Model):
    created_at = models.CharField(max_length=100)
    text = models.CharField(max_length=2000)
    url = models.URLField(max_length=200)
    countries = models.ManyToManyField(Country, blank=True)

    def __str__(self):
        return 'Tweet made at {}'.format(self.created_at)

    @staticmethod
    def get_tweets():
        url = 'https://api.twitter.com/1.1/account/verify_credentials.json'
        auth = OAuth1('M72BiZ9828A9ERCIwAZxaDLkJ', '94Tpp7CYXlCbyTBMSQj2aE399Hvvbe51UdQVuZWwD9vlBgcaeB',
                      '949738713399070720-UGUwHUu7C2PxtrK1sAFh5e8XvM4QU4d',
                      'i2dcngnHbUw58bwDGplWoEzFGaWfsxKP2TpOOdyqxOMNV')
        resp = requests.get(
            'https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=MaplecroftRisk&count=50', auth=auth)
        country_list = []
        with open('assignment/countries.csv') as f:
            reader = csv.reader(f)
            for a in reader:
                if a and a[0]:
                    country_list.append(a[0])
        for a in resp.json():
                try:
                    obj = Tweet.objects.get(created_at=a['created_at'], text=a['text'],
                                            url='https://twitter.com/MaplecroftRisk/status/{}'.format(a['id_str']))
                except Tweet.DoesNotExist:
                    obj = Tweet(created_at=a['created_at'], text=a['text'],
                                url='https://twitter.com/MaplecroftRisk/status/{}'.format(a['id_str']))
                    obj.save()
                    country_instances = []
                    for b in country_list:
                        if b in obj.text:
                            country_instances.append(Country.objects.get(name=b))
                            obj.countries.add(*country_instances)

tweet-map/app/views.py
from django.views import generic
from .models import Country, Tweet


class CountryListView(generic.ListView):
    model = Country
    template_name = 'app/country_list.html'

    def get_queryset(self):
        tweeted_about = Country.objects.filter(tweet__isnull=False)
        return tweeted_about


class TweetMapView(generic.ListView):
    model = Country
    template_name = 'app/tweet_map.html'

    def get_queryset(self):
        tweeted_about = Country.objects.filter(tweet__isnull=False)
        return tweeted_about


class CountryDetailView(generic.DetailView):
    model = Country


class TweetListView(generic.ListView):
    model = Tweet
    template_name = 'app/tweet_list.html'

    def get_queryset(self):
        tweets = Tweet.objects.all()[:50]
        return tweets

tweet-map/app/templates/app/country_detail.html
{% extends "base_generic.html" %}
{% block content %}
  <h2>{{ country.name }}: Country Information</h2>
    <h4>Country code: {{ country.code }}</h4>
{% endblock %}

tweet-map/app/templates/app/country_list.html
{% extends "base_generic.html" %}
{% block content %}
<h3>Referenced Countries</h3>
   {% if object_list %}
    <ul>
      {% for a in object_list %}
      <li><h4>
        <a href="{{ a.get_absolute_url }}">{{ a.name }}</a><br>
          {% for tweet in a.tweet_set.all %}
        {{tweet.text}}
    {% endfor %}
       </h4></li>
      {% endfor %}
      {% endif %}
    </ul>
{% endblock %}

tweet-map/app/templates/app/tweet_list.html
{% extends "base_generic.html" %}
{% block content %}
<h3>@MaplecroftRisk Latest 50 Tweets</h3>
   {% if object_list %}
    <ul>
      {% for a in object_list %}
      <li>
          {{ a.text }}
          <a href="{{ a.url }}">{{ a.url }}</a>
                  {{ a.created_at }}
       </li>
        <br>
      {% endfor %}
      {% endif %}
    </ul>
{% endblock %}

tweet-map/app/templates/app/tweet_map.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Tweet Map</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" type="text/css"href="{% static 'css/styles.css' %}">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {
        'packages':['geochart'],
        // Note: you will need to get a mapsApiKey for your project.
        // See: https://developers.google.com/chart/interactive/docs/basic_load_libs#load-settings
        'mapsApiKey': 'AIzaSyDCPTEH0vyT91giedWB3u-geHSVWtl3pm4'
      });
      google.charts.setOnLoadCallback(drawRegionsMap);

      function drawRegionsMap() {
        var data = google.visualization.arrayToDataTable(
        [['Country', 'Tweets'],
        {% for a in object_list %}
        ['{{ a.name }}', {{ a.tweet_set.all|length }}],
        {% endfor %}]
        );

        var options = {};

        var chart = new google.visualization.GeoChart(document.getElementById('regions_div'));

        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
  <div class="container-fluid">
        <img src="{% static 'images/header.png' %}" style='width: 100%; object-fit: contain' />
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <br>
      <ul class="sidebar-nav">
          <li><a href="{% url 'tweet_list' %}">Latest 50 tweets</a></li>
          <li><a href="{% url 'tweet_map' %}">Map of associated countries</a></li>
        <li><a href="{% url 'countries' %}">List of associated countries</a></li>
      </ul>
      <br>
     <img src="{% static 'images/logo.png' %}" style='margin-left: 2em; width: 50%; height: 50%' />
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
    <div id="regions_div" style="width: 900px; height: 500px;"></div>
      </div>
    </div>
  </div>
</body>
</html>

tweet-map/app/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Maplecroft Twitter Feed</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" type="text/css"href="{% static 'css/styles.css' %}">
</head>
<body>
<style>
body {background-color: #FFFAFA;}
h3   {color: #708090;}
</style>
  <div class="container-fluid">
        <img src="{% static 'images/header.png' %}" style='width: 100%; object-fit: contain' />
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <br>
      <ul class="sidebar-nav">
          <li><a href="{% url 'tweet_list' %}">Latest 50 tweets</a></li>
          <li><a href="{% url 'tweet_map' %}">Map of associated countries</a></li>
        <li><a href="{% url 'countries' %}">List of associated countries</a></li>
      </ul>
      <br>
     <img src="{% static 'images/logo.png' %}" style='margin-left: 2em; width: 50%; height: 50%' />
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</body>
</html>